name: Automerge
on: [push]
jobs:
  job1:
    name: Pruebas
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'MERGE')
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v3
    - name: Configuración de entorno de python
      uses: actions/setup-python@v3
      with:
          python-version: "3.9"
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest discover -s tests -v
    - name: Cálculo de cubrimiento
      id: cubrimiento
      run: |
          coverage run -m unittest discover -s tests -v
          coverage report -m
  automerge:
      name: Mezcla rama -> develo
      needs: job1
      runs-on: ubuntu-latest
      if: contains(github.event.head_commit.message, 'MERGE')
      steps:
        - name: Merge rama -> develop
          uses: tukasz/direct-merge-action@master
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            source-branch: ${{ github.ref }}
            target-branch: develop
            commit-message: "Se hace merge a la rama develop"
