name: Workflow Rama Release
on:
  push:
    branches: [ develop ]
jobs:
    Crear-release:
      name: Crear rama release
      runs-on: ubuntu-latest
      if: contains(github.event.head_commit.message, 'RELEASE')
      steps:      
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Crear rama release
        run: |
          git checkout -b release
          git push -f -u origin release
    Pruebas:
      name: Pruebas
      runs-on: ubuntu-latest
      needs: Crear-release
      steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configuración de entorno
        if: github.ref == 'refs/heads/release'
        uses: actions/setup-python@v3
        with:
            python-version: '3.9'
      - name: Instalación de dependencias
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: correr pruebas
        run: |
          python -m unittest -v tests
        if: ${{ success() }}
      - name: Mezcla release -> main
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: release
          target-branch: main
          commit-message: "Se hace merge de la rama release con la rama main"
